### ISSUE TITLE
Feature request: display human-readable ATEM input and HyperDeck clip names

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/SuperConductor#69]
**Is your feature request related to a problem? Please describe.**
When creating rundowns that switch ATEM inputs or play HyperDeck clips, these timeline objects are currently displayed by numeric ID only. It would be helpful to the operator if they could also see the name of that input or clip as it exists on the device.

**Describe the solution you'd like**
For ATEM inputs, I'd like to see the name of the input (its [`longName`](https://nrkno.github.io/sofie-atem-connection/interfaces/InputState.InputChannel.html#longName) and maybe also its [`shortName`](https://nrkno.github.io/sofie-atem-connection/interfaces/InputState.InputChannel.html#shortName)) in two places:

1. The `Input` field in the inspector. This means that this field could become a fuzzy finding combo box dropdown thing that enumerates all the available inputs by both numeric ID and human readable name.
2. The label of the object on the timeline.

![atemme](https://user-images.githubusercontent.com/873012/186709440-a51ca543-d666-4f9e-9688-bd0671c347d8.png)

For HyperDeck clips, I'd like to see the same thing but for clip names instead.

**Additional context**
The HyperDeck functionality isn't merged yet but probably will be soon.

Also, this feature seems like it might require some pretty hefty changes to how SuperConductor handles resources. Maybe I'm not thinking about it clearly though.

There are a number of challenges that might come with this feature, such as:

- What if a user wants to pre-configure a rundown without currently being connected to an ATEM or HyperDeck? Do we show cached names where we can or do we play it safe and show no names?
- How would we feed the timeline object's `resource` (which is probably what would contain the human-readable identifiers) to [`describeTimelineObject`](https://github.com/SuperFlyTV/SuperConductor/blob/a1cbd8811dfb68693e0537108709e6848925e693/apps/app/src/lib/TimelineObj.ts#L15), the function which generates the timeline object labels?
- How would we reactively update the labels of these timeline objects when someone changes the name of an input on the ATEM or swaps out clips on a HyperDeck?
- What happens if someone was connected to, say, a 4 M/E Constellation and then changes it to be a 1 M/E Production Studio? They don't have the same number of inputs and M/Es, so should we display some kind of warning that some of the timeline objects are no longer valid for the target ATEM?

**Comment by nytamin** [comment]
These are pretty good ideas, I'd say!

Implementation-wise, I'm not quite certain, but I believe we might get this done without too much reworking of the Resource-handling of things, I'm thinking that the Atem-device could expose its different inputs as multiple resources and put a label on the different ones. Then the Input field could construct a drop-down selector using this information.

>What if a user wants to pre-configure a rundown?
This will probably be hard to do with any device, since we might not know the topology of it beforehand. So we would have to fall back to displaying integers in the settings etc..

>How would we reactively update the labels of these timeline objects when someone changes the name of an input on the ATEM?
The resources would be reloaded when the user click reload, or if auto-reload is enabled 
![image](https://user-images.githubusercontent.com/15196563/187348950-aac40171-1841-4985-9a9f-d6ee623a6a2d.png)

>What happens if the hardware changes?
I think the GUI should be able to fall back to using raw values (integers etc) if it can't match the values to a Resouces, and also allow a user to input a raw value instead of picking from a pre-populated list.
That way, we can ensure we always display _something which is true_ to the user, and I think that's the best we can do :)


Feel free to submit a Pull Request with this, I'd be happy to provide feedback and help out along the way 👍

**Comment by nytamin** [comment]
Implemented in [Release v0.12.0-alpha.0](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.12.0-alpha.0)
