### ISSUE TITLE
Feature request: add option to allow Parts to keep playing past their scheduled duration (without an infinite) and log how much time they went over

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/SuperConductor#76]
**Is your feature request related to a problem? Please describe.**
I've got an operator who is mixing SuperConductor with manual control. I know this is not the primary use case for SuperConductor, but it's something that will probably come up more in the future. The way they are utilizing SuperConductor is as follows:

1. Use SuperConductor to play one or more HyperDeck clips.
2. Use SuperConductor to dispatch an OSC command to Companion which switches inputs on an ATEM and/or vMix.
    - They don't use SuperConductor to control the ATEM/vMix directly because of the fact that TSR resets things back to a default state when there are no corresponding timeline objects active, which clashes with their manual switching. OSC commands are fire-and-forget which avoids this problem.
3. Manually control the ATEM/vMix for several hours.
4. Meanwhile, the Part with the OSC command is continuing to play. It will have a duration that is the same as the scheduled duration of the live segment being switched on the ATEM/vMix.
5. If the live segment is going to go over time, the operator must hastily increase the duration of the OSC timeline object to avoid it auto-stepping to the next Part, which is another HyperDeck clip.
6. (**This is the important bit**) Record precisely how long the live segment went over time. This is what they'd like SuperConductor to keep track of.
7. Use that time information elsewhere in the production.
8. Go to 1 and repeat.

**Describe the solution you'd like**
The operator in question would like the option to allow a Part to "roll" past its scheduled duration, but keep track of how long it has gone over time and then make that value available for easy copy/pasting.

**Additional context**
Is there a better way to achieve the desired result? This may be out-of-scope for SuperConductor. I'd like @nytamin's feedback before deciding if this should be pursued or marked as `wontfix` (same goes for most of the issues I've opened).

**Comment by nytamin** [comment]
There currently isn't any time-tracking bits like you describe in SuperConductor. I think that this might be out of scope (though if there is a clearer use-case I'm open to discussing it).
If it's time tracking you're after, maybe an OSC-command could be fired off somewhere to start a timer or something? 🙂

**Comment by alvancamp** [comment]
Thanks for the feedback. I'm going to mark this as `wontfix` for now because I agree that it feels out of scope.

**Comment by jstarpl** [comment]
This sounds like a very good example of something that could be a time-tracking extension of sorts. The way I see it, the Part would be infinite, but it could have an additional metadata of "duration budget" that the time tracking extension would use and do the countdowns.

I did spend some time investigating how the extension API could look like, I think I would mainly like to base it off VS Code's extension system, since that has a thriving extension market. I'm wondering what other sorts of data/API's would be needed to build such an extension.

@alvancamp What would the "Use that time information elsewhere in the production." look like? Just manually output that in some sort of a view? Send it out using OSC? Send out an HTTP request after the Part has finished to update some rundown system?
